### ISSUE TITLE
Option to edit/view pkgbuilds and other external scripts.

### ISSUE THREAD

**Issue by Phate6660** [kiedtl/knaur#1]
I love it so far. It's faster than the one I'm currently using. However, I really like how my current one (Trizen) forces you to view pkgbuilds and any external scripts included with the package you are trying to install, then gives you the option of editing them if you want to.

This kind of functionality is very important, for 2 reasons (to me anyways):

- It gives ease of mind to security-oriented people. So they know everything that's going to happen.
- Certain packages like mpv-git require you to edit the pkgbuild to enable some features that you have to manually specify.

**Comment by kiedtl** [comment]
Kay, I'll add a prompt for that.
